import teamImage from '../Asset/file_00000000978881f5b8dd22e28b780b49.png';
import cleanoutImage from '../Asset/file_0000000096cc81f58f838e2774e509ca.png';
import greenWasteImage from '../Asset/file_00000000255c81faadc0cb8a3afdd725.png';
import customerImage from '../Asset/dump_runnerz_19.jpg.jpeg';
import './about-us-page.css';

function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function AboutUsPage() {
  return <div className="about-page">
    <section className="about-hero"><div className="container about-hero-inner"><div><p className="eyebrow">THE DUMP RUNNERZ STORY</p><h1>More space.<br /><em>Less stress.</em></h1><p>We make junk removal simple for homes, businesses and the people who need a clear space without the heavy lifting.</p><div className="about-hero-actions"><a className="button button-primary" href="/book-appointment">Book a Pickup <Arrow /></a><a className="button button-ghost" href="tel:1800555867">Call 1800 555 867</a></div></div><div className="about-hero-photo"><img src={teamImage} alt="DUMP RUNNERZ team carrying furniture to a removal truck" /><span>WE LOAD.<br /><strong>YOU RELAX.</strong></span></div></div></section>

    <section className="about-intro"><div className="container about-intro-grid"><div><p className="eyebrow">WHO WE ARE</p><h2>Junk removal<br /><em>done properly.</em></h2></div><div><p>DUMP RUNNERZ is a full-service junk removal team built to take the hassle out of clearing unwanted items. From one bulky piece of furniture to a larger property clean-out, we help you get your space back.</p><p>Our approach is straightforward: understand what needs to go, handle the lifting and loading, and keep the process clear from start to finish.</p><a className="text-link" href="/what-we-do">See what we do <Arrow /></a></div></div></section>

    <section className="about-values"><div className="container"><div className="about-centered"><p className="eyebrow">WHAT MATTERS TO US</p><h2>A better experience<br /><em>from start to finish.</em></h2></div><div className="about-value-grid"><article><span>01</span><div className="about-value-icon">✦</div><h3>Make it easy</h3><p>Clear information, simple booking and a team that handles the hard work.</p></article><article><span>02</span><div className="about-value-icon">⌖</div><h3>Respect your space</h3><p>We work carefully around homes, offices and the areas that matter to you.</p></article><article><span>03</span><div className="about-value-icon">♻</div><h3>Think responsibly</h3><p>Reusable items may be donated and eligible materials recycled where possible.</p></article></div></div></section>

    <section className="about-feature"><div className="container about-feature-grid"><img loading="lazy" src={cleanoutImage} alt="DUMP RUNNERZ crew removing unwanted household items" /><div><p className="eyebrow">FULL-SERVICE SUPPORT</p><h2>Point to the junk.<br /><em>We’ll take it from here.</em></h2><p>You do not need to sort, carry or load everything yourself. Tell us what needs to be removed and where it is located, then our team will take care of the approved items.</p><div className="about-checks"><span>✓ Residential and commercial support</span><span>✓ Furniture, appliances and general clutter</span><span>✓ Green waste and eligible project debris</span></div><a className="button button-dark" href="/book-appointment">Get an Estimate <Arrow /></a></div></div></section>

    <section className="about-process"><div className="container"><div className="about-process-heading"><div><p className="eyebrow">HOW WE WORK</p><h2>A clear process<br /><em>you can trust.</em></h2></div><p>Every clear-out is different, so we keep the next steps simple and easy to understand.</p></div><div className="about-process-grid"><article><b>01</b><h3>Tell us what you need</h3><p>Book online or contact our team with the items and location details.</p></article><article><b>02</b><h3>Review the details</h3><p>We discuss the job and provide the service details for your request.</p></article><article><b>03</b><h3>Enjoy your space</h3><p>Once approved, our crew handles the lifting, loading and removal.</p></article></div></div></section>

    <section className="about-human"><div className="container about-human-grid"><div><p className="eyebrow">A TEAM YOU CAN TALK TO</p><h2>Helpful people.<br /><em>Practical service.</em></h2><p>Good junk removal is about more than taking items away. It is about listening to what you need, communicating clearly and leaving you with a space that feels easier to use.</p><a className="text-link" href="/contact-us">Talk to our team <Arrow /></a></div><img loading="lazy" src={customerImage} alt="DUMP RUNNERZ team member speaking with a customer" /></div></section>

    <section className="about-responsible"><div className="container about-responsible-grid"><img loading="lazy" src={greenWasteImage} alt="DUMP RUNNERZ team loading green waste" /><div><p className="eyebrow">RESPONSIBLE REMOVAL</p><h2>Clear space.<br /><em>Consider the next step.</em></h2><p>We consider donation, reuse and recycling opportunities where possible. Remaining items are handled through appropriate disposal for the service and location.</p><a className="text-link" href="/what-we-take">See what we take <Arrow /></a></div></div></section>

    <section className="about-final"><div className="container"><div><p className="eyebrow">LET’S GET STARTED</p><h2>Ready to make room<br /><em>for what matters?</em></h2><p>Tell us what needs to go and choose a convenient appointment time.</p></div><a className="button button-primary" href="/book-appointment">Book a Pickup <Arrow /></a></div></section>
  </div>;
}
