import { useEffect, useState } from 'react';
import './admin-page.css';
import { LoadingScreen } from '../components/AppFeedback';

const API = import.meta.env.VITE_API_URL || 'https://dump-runner-remover-server.onrender.com';

async function apiRequest(path, options = {}) {
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('dumpRunnerzToken') || ''}`, ...options.headers } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.message || 'Request failed.');
  return data;
}

export default function AdminPage() {
  const [admin, setAdmin] = useState(() => { try { return JSON.parse(localStorage.getItem('dumpRunnerzUser') || 'null'); } catch { return null; } });
  const [authenticated, setAuthenticated] = useState(false);
  const [authChecking, setAuthChecking] = useState(true);
  const [view, setView] = useState('overview');
  const [bookings, setBookings] = useState([]);
  const [users, setUsers] = useState([]);
  const [messages, setMessages] = useState([]);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [loginForm, setLoginForm] = useState({ email: '', password: '' });
  const [passwordForm, setPasswordForm] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });

  useEffect(() => { document.title = authenticated ? 'Admin Dashboard | DUMP RUNNERZ' : 'Admin Access | DUMP RUNNERZ'; }, [authenticated]);
  useEffect(() => {
    const verifySession = async () => {
      if (!localStorage.getItem('dumpRunnerzToken')) { setAuthChecking(false); return; }
      try { const data = await apiRequest('/api/auth/me'); setAdmin(data.user); setAuthenticated(true); } catch { localStorage.removeItem('dumpRunnerzToken'); localStorage.removeItem('dumpRunnerzUser'); setAuthenticated(false); } finally { setAuthChecking(false); }
    };
    verifySession();
  }, []);
  useEffect(() => { const protectBack = () => { if (!localStorage.getItem('dumpRunnerzToken')) { setAuthenticated(false); window.location.replace('/sign-in'); } }; window.addEventListener('pageshow', protectBack); return () => window.removeEventListener('pageshow', protectBack); }, []);

  const loadBookings = async () => { try { const data = await apiRequest('/api/bookings'); setBookings((data.bookings || []).map((booking) => ({ ...booking, id: booking._id || booking.id }))); } catch (requestError) { setError(requestError.message); } };
  const loadUsers = async () => { try { const data = await apiRequest('/api/users'); setUsers(data.users || []); } catch (requestError) { setError(requestError.message); } };
  const loadMessages = async () => { try { const data = await apiRequest('/api/contact-messages'); setMessages(data.messages || []); } catch (requestError) { setError(requestError.message); } };
  const openView = (nextView) => { setError(''); setNotice(''); setView(nextView); if (nextView === 'bookings') loadBookings(); if (nextView === 'users') loadUsers(); if (nextView === 'messages') loadMessages(); };
  const deleteMessage = async (id) => { if (!window.confirm('Remove this contact message?')) return; try { await apiRequest(`/api/contact-messages/${id}`, { method: 'DELETE' }); setMessages((current) => current.filter((item) => item._id !== id)); } catch (requestError) { setError(requestError.message); } };
  const markMessageRead = async (message) => { if (message.status === 'Read') return; try { const data = await apiRequest(`/api/contact-messages/${message._id}/status`, { method: 'PATCH', body: JSON.stringify({ status: 'Read' }) }); setMessages((current) => current.map((item) => item._id === message._id ? data.contactMessage : item)); } catch (requestError) { setError(requestError.message); } };
  const login = async (event) => { event.preventDefault(); setError(''); try { const data = await apiRequest('/api/auth/admin-login', { method: 'POST', body: JSON.stringify(loginForm) }); localStorage.setItem('dumpRunnerzToken', data.token); localStorage.setItem('dumpRunnerzUser', JSON.stringify(data.user)); window.dispatchEvent(new Event('dumpRunnerz-auth-change')); setAdmin(data.user); setAuthenticated(true); } catch (requestError) { setError(requestError.message); } };
  const changePassword = async (event) => { event.preventDefault(); setError(''); setNotice(''); if (passwordForm.newPassword !== passwordForm.confirmPassword) return setError('New passwords do not match.'); try { const data = await apiRequest('/api/auth/admin-password', { method: 'POST', body: JSON.stringify({ currentPassword: passwordForm.currentPassword, newPassword: passwordForm.newPassword }) }); setPasswordForm({ currentPassword: '', newPassword: '', confirmPassword: '' }); setNotice(data.message); } catch (requestError) { setError(requestError.message); } };
  const logout = () => { localStorage.removeItem('dumpRunnerzToken'); localStorage.removeItem('dumpRunnerzUser'); window.dispatchEvent(new Event('dumpRunnerz-auth-change')); setAuthenticated(false); window.location.replace('/sign-in'); };

  if (authChecking) return <LoadingScreen message="Verifying admin access…" />;
  if (!authenticated) return <div className="admin-page admin-gate"><div className="admin-gate-card"><div className="admin-logo"><img src="/dump-runnerz-logo.jpeg" alt="DUMP RUNNERZ" /></div><p className="admin-kicker">DUMP RUNNERZ ADMIN</p><h1>Welcome back</h1><p className="admin-subtitle">Sign in to manage bookings, messages and registered users.</p><form onSubmit={login} className="admin-form"><label htmlFor="admin-email">Admin email</label><input id="admin-email" type="email" value={loginForm.email} onChange={(event) => setLoginForm({ ...loginForm, email: event.target.value })} required /><label htmlFor="admin-password">Password</label><input id="admin-password" type="password" value={loginForm.password} onChange={(event) => setLoginForm({ ...loginForm, password: event.target.value })} required />{error && <p className="admin-error" role="alert">{error}</p>}<button className="button button-primary" type="submit">Sign In to Dashboard <span>→</span></button></form></div></div>;

  const pageTitle = { overview: 'Good morning, admin.', bookings: 'Bookings', messages: 'Contact messages', users: 'Registered users', settings: 'Account settings' }[view];
  return <div className="admin-page"><div className="admin-dashboard"><aside className="admin-sidebar"><div className="admin-sidebar-brand"><img src="/dump-runnerz-logo.jpeg" alt="DUMP RUNNERZ" /></div><p className="admin-kicker">CONTROL CENTRE</p><button className={view === 'overview' ? 'active' : ''} onClick={() => openView('overview')} type="button">▦ <span>Overview</span></button><button className={view === 'bookings' ? 'active' : ''} onClick={() => openView('bookings')} type="button">▣ <span>Bookings <b className="booking-count">{bookings.length}</b></span></button><button className={view === 'messages' ? 'active' : ''} onClick={() => openView('messages')} type="button">✉ <span>Messages <b className="booking-count">{messages.filter((item) => item.status === 'New').length}</b></span></button><button className={view === 'users' ? 'active' : ''} onClick={() => openView('users')} type="button">♙ <span>Users <b className="booking-count">{users.length}</b></span></button><button className={view === 'settings' ? 'active' : ''} onClick={() => openView('settings')} type="button">⚙ <span>Settings</span></button><button className="admin-sidebar-logout" onClick={logout} type="button">↪ <span>Sign out</span></button></aside><main className="admin-content"><header className="admin-topbar"><div><p className="admin-kicker">DUMP RUNNERZ ADMIN</p><h1>{pageTitle}</h1></div><div className="admin-avatar">{admin?.email?.slice(0, 1).toUpperCase()}</div></header>{notice && <div className="admin-success">✓ {notice}</div>}{error && <div className="admin-error admin-content-error">{error}</div>}
  {view === 'overview' && <><div className="admin-stat-grid"><div><span>Bookings</span><strong>{bookings.length}</strong><small>Stored in MongoDB</small></div><div><span>Contact messages</span><strong>{messages.length}</strong><small>Customer inquiries</small></div><div><span>Registered users</span><strong>{users.length}</strong><small>Customer accounts</small></div></div><section className="admin-panel"><div><p className="admin-kicker">DATABASE ACTIVITY</p><h2>Manage your customer data</h2><p>View appointment requests, contact messages and registered accounts from MongoDB.</p></div><button className="button button-primary" type="button" onClick={() => openView('messages')}>View messages <span>→</span></button></section></>}
  {view === 'bookings' && <BookingsView bookings={bookings} />}
  {view === 'messages' && <MessagesView messages={messages} onRead={markMessageRead} onDelete={deleteMessage} />}
  {view === 'users' && <UsersView users={users} />}
  {view === 'settings' && <section className="admin-panel admin-settings"><p className="admin-kicker">SECURITY</p><h2>Change admin password</h2><p>Update the password used to access this dashboard.</p><form className="admin-form" onSubmit={changePassword}><label htmlFor="current-password">Current password</label><input id="current-password" type="password" value={passwordForm.currentPassword} onChange={(event) => setPasswordForm({ ...passwordForm, currentPassword: event.target.value })} required /><label htmlFor="new-password">New password</label><input id="new-password" type="password" value={passwordForm.newPassword} onChange={(event) => setPasswordForm({ ...passwordForm, newPassword: event.target.value })} minLength="6" required /><label htmlFor="confirm-new-password">Confirm new password</label><input id="confirm-new-password" type="password" value={passwordForm.confirmPassword} onChange={(event) => setPasswordForm({ ...passwordForm, confirmPassword: event.target.value })} minLength="6" required /><button className="button button-primary" type="submit">Update password <span>→</span></button></form></section>}</main></div></div>;
}

function BookingsView({ bookings }) { return <section className="admin-bookings">{bookings.length === 0 ? <div className="admin-panel admin-empty"><h2>No bookings yet</h2><p>Customer appointment requests will appear here.</p></div> : bookings.map((booking) => <article className="booking-record" key={booking.id}><div className="booking-record-top"><div><span className="booking-id">{booking.bookingId || booking.id}</span><h2>{booking.firstName} {booking.lastName}</h2></div><span className="booking-status">{booking.status}</span></div><div className="booking-record-grid"><div><small>Service</small><strong>{booking.service}</strong></div><div><small>Appointment</small><strong>{booking.dateLabel} · {booking.time}</strong></div><div><small>Contact</small><strong>{booking.phone}</strong><span>{booking.email}</span></div><div><small>Pickup address</small><strong>{booking.address}</strong><span>{booking.suburb}{booking.state ? `, ${booking.state}` : ''}</span></div></div>{booking.notes && <p className="booking-notes"><b>Notes:</b> {booking.notes}</p>}</article>)}</section>; }

function UsersView({ users }) { return <section className="admin-users">{users.length === 0 ? <div className="admin-panel admin-empty"><h2>No registered users</h2><p>New accounts will appear here after registration.</p></div> : users.map((user) => <article className="user-record" key={user._id}><div className="user-avatar">{user.name?.slice(0, 1).toUpperCase()}</div><div className="user-record-info"><h2>{user.name}</h2><span>{user.email}</span><small>Registered {new Date(user.createdAt).toLocaleDateString('en-AU')}</small></div><span className={`user-role ${user.role === 'admin' ? 'admin-role' : ''}`}>{user.role || 'customer'}</span></article>)}</section>; }

function MessagesView({ messages, onRead, onDelete }) { return <section className="admin-messages">{messages.length === 0 ? <div className="admin-panel admin-empty"><h2>No contact messages</h2><p>Messages submitted from the Contact Us page will appear here.</p></div> : messages.map((item) => <article className={`message-record ${item.status === 'New' ? 'is-new' : ''}`} key={item._id} onClick={() => onRead(item)}><div className="message-record-top"><div><span className="message-subject">{item.subject}</span><h2>{item.name}</h2></div><span className={`message-status ${item.status === 'New' ? 'new-status' : ''}`}>{item.status}</span></div><div className="message-record-grid"><div><small>Email</small><a href={`mailto:${item.email}`}>{item.email}</a></div><div><small>Phone</small><span>{item.phone || 'Not provided'}</span></div><div><small>Received</small><span>{new Date(item.createdAt).toLocaleString('en-AU')}</span></div></div><p className="message-body">{item.message}</p><button className="message-delete" type="button" onClick={(event) => { event.stopPropagation(); onDelete(item._id); }}>Delete message</button></article>)}</section>; }
